name: "Aditya Relangi"
description: "Aditya Relangi's website"
author: "Aditya Relangi"

url: "https://adityarelangi.com"
baseurl: ""

markdown: kramdown
permalink: /blog/:title
highlighter: rouge

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - .DS_Store
  - .git
  - .gitignore
  - README.md

# HTML Compression
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Performance optimizations
sass:
  style: compressed